global:
  scrape_interval: 5s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'ecommerce-app'
    static_configs:
      - targets: ['ecommerce-app:8000']
